# Generated by Django 5.0.6 on 2024-07-17 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(default=1, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'wmv'])]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LessonVideo',
        ),
    ]
